spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
  security:
    user:
      name: Bucky
todos:
  webui:
    placeholder: "Learn Podman!"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.todos: TRACE
