spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
todos:
  webui:
    placeholder: 'Time to wash the car'
management:
  endpoints:
    web:
      exposure:
        include: '*'
