spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
todos:
  webui:
    placeholder: "Time to wash the dog?"
management:
  endpoints:
    web:
      exposure:
        include: '*'
