spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
  security:
    user:
      name: Bucky
todos:
  webui:
    placeholder: "Time to wash the dog?"
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.todos: TRACE
